# Generated by Django 5.2.7 on 2025-10-28 09:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=120)),
                ('nombres', models.CharField(max_length=120)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('idioma', models.CharField(blank=True, max_length=60)),
                ('editorial', models.CharField(blank=True, max_length=120)),
                ('edicion', models.CharField(blank=True, max_length=50)),
                ('anio', models.PositiveIntegerField(help_text='Año de publicación', validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2025)])),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('cantidad_ejemplares', models.PositiveIntegerField(default=1, help_text='Cantidad de copias del libro en la biblioteca', validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('baja', 'Baja')], default='disponible', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='gestion_libros.autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
