# Generated by Django 5.2.7 on 2025-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=120)),
                ('nombres', models.CharField(max_length=120)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
