# Generated by Django 5.2.7 on 2025-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_socio', models.PositiveIntegerField(unique=True)),
                ('apellidos', models.CharField(max_length=120)),
                ('nombres', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('baja', 'Baja')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
